services:
  - type: web
    name: pdf-table-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
