services:
  - type: web
    name: pdf-table-extractor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
